// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    using System;
    using System.Buffers;
    using MessagePack;

    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<Type, int>(12)
            {
                { typeof(global::Intense.Master.BaseMaster), 0 },
                { typeof(global::Intense.Master.VersionMaster), 1 },
                { typeof(global::Intense.Master.TitleMaster), 2 },
                { typeof(global::Intense.Master.SongSelectMaster), 3 },
                { typeof(global::Intense.Master.SongMaster), 4 },
                { typeof(global::Intense.Master.SongScoreRateMaster), 5 },
                { typeof(global::Intense.Master.SongJudgeZoneMaster), 6 },
                { typeof(global::Intense.Master.SongHpRateMaster), 7 },
                { typeof(global::Intense.Master.ResultMaster), 8 },
                { typeof(global::Intense.Master.SoundSheetNameMaster), 9 },
                { typeof(global::Intense.Master.TutorialStepMaster), 10 },
                { typeof(global::Intense.Master.TutorialMaster), 11 },
            };
        }

        internal static object GetFormatter(Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new MessagePack.Formatters.Intense.Master.BaseMasterFormatter();
                case 1: return new MessagePack.Formatters.Intense.Master.VersionMasterFormatter();
                case 2: return new MessagePack.Formatters.Intense.Master.TitleMasterFormatter();
                case 3: return new MessagePack.Formatters.Intense.Master.SongSelectMasterFormatter();
                case 4: return new MessagePack.Formatters.Intense.Master.SongMasterFormatter();
                case 5: return new MessagePack.Formatters.Intense.Master.SongScoreRateMasterFormatter();
                case 6: return new MessagePack.Formatters.Intense.Master.SongJudgeZoneMasterFormatter();
                case 7: return new MessagePack.Formatters.Intense.Master.SongHpRateMasterFormatter();
                case 8: return new MessagePack.Formatters.Intense.Master.ResultMasterFormatter();
                case 9: return new MessagePack.Formatters.Intense.Master.SoundSheetNameMasterFormatter();
                case 10: return new MessagePack.Formatters.Intense.Master.TutorialStepMasterFormatter();
                case 11: return new MessagePack.Formatters.Intense.Master.TutorialMasterFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1649 // File name should match first type name



// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Intense.Master
{
    using System;
    using System.Buffers;
    using System.Collections.Generic;
    using MessagePack;

    public sealed class BaseMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.BaseMaster>
    {
        private readonly Dictionary<RuntimeTypeHandle, KeyValuePair<int, int>> typeToKeyAndJumpMap;
        private readonly Dictionary<int, int> keyToJumpMap;

        public BaseMasterFormatter()
        {
            this.typeToKeyAndJumpMap = new Dictionary<RuntimeTypeHandle, KeyValuePair<int, int>>(11, global::MessagePack.Internal.RuntimeTypeHandleEqualityComparer.Default)
            {
                { typeof(global::Intense.Master.VersionMaster).TypeHandle, new KeyValuePair<int, int>(0, 0) },
                { typeof(global::Intense.Master.TitleMaster).TypeHandle, new KeyValuePair<int, int>(1, 1) },
                { typeof(global::Intense.Master.SongSelectMaster).TypeHandle, new KeyValuePair<int, int>(2, 2) },
                { typeof(global::Intense.Master.SongMaster).TypeHandle, new KeyValuePair<int, int>(3, 3) },
                { typeof(global::Intense.Master.SongScoreRateMaster).TypeHandle, new KeyValuePair<int, int>(4, 4) },
                { typeof(global::Intense.Master.SongJudgeZoneMaster).TypeHandle, new KeyValuePair<int, int>(5, 5) },
                { typeof(global::Intense.Master.SongHpRateMaster).TypeHandle, new KeyValuePair<int, int>(6, 6) },
                { typeof(global::Intense.Master.ResultMaster).TypeHandle, new KeyValuePair<int, int>(7, 7) },
                { typeof(global::Intense.Master.SoundSheetNameMaster).TypeHandle, new KeyValuePair<int, int>(8, 8) },
                { typeof(global::Intense.Master.TutorialStepMaster).TypeHandle, new KeyValuePair<int, int>(9, 9) },
                { typeof(global::Intense.Master.TutorialMaster).TypeHandle, new KeyValuePair<int, int>(10, 10) },
            };
            this.keyToJumpMap = new Dictionary<int, int>(11)
            {
                { 0, 0 },
                { 1, 1 },
                { 2, 2 },
                { 3, 3 },
                { 4, 4 },
                { 5, 5 },
                { 6, 6 },
                { 7, 7 },
                { 8, 8 },
                { 9, 9 },
                { 10, 10 },
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.BaseMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            KeyValuePair<int, int> keyValuePair;
            if (value != null && this.typeToKeyAndJumpMap.TryGetValue(value.GetType().TypeHandle, out keyValuePair))
            {
                writer.WriteArrayHeader(2);
                writer.WriteInt32(keyValuePair.Key);
                switch (keyValuePair.Value)
                {
                    case 0:
                        options.Resolver.GetFormatterWithVerify<global::Intense.Master.VersionMaster>().Serialize(ref writer, (global::Intense.Master.VersionMaster)value, options);
                        break;
                    case 1:
                        options.Resolver.GetFormatterWithVerify<global::Intense.Master.TitleMaster>().Serialize(ref writer, (global::Intense.Master.TitleMaster)value, options);
                        break;
                    case 2:
                        options.Resolver.GetFormatterWithVerify<global::Intense.Master.SongSelectMaster>().Serialize(ref writer, (global::Intense.Master.SongSelectMaster)value, options);
                        break;
                    case 3:
                        options.Resolver.GetFormatterWithVerify<global::Intense.Master.SongMaster>().Serialize(ref writer, (global::Intense.Master.SongMaster)value, options);
                        break;
                    case 4:
                        options.Resolver.GetFormatterWithVerify<global::Intense.Master.SongScoreRateMaster>().Serialize(ref writer, (global::Intense.Master.SongScoreRateMaster)value, options);
                        break;
                    case 5:
                        options.Resolver.GetFormatterWithVerify<global::Intense.Master.SongJudgeZoneMaster>().Serialize(ref writer, (global::Intense.Master.SongJudgeZoneMaster)value, options);
                        break;
                    case 6:
                        options.Resolver.GetFormatterWithVerify<global::Intense.Master.SongHpRateMaster>().Serialize(ref writer, (global::Intense.Master.SongHpRateMaster)value, options);
                        break;
                    case 7:
                        options.Resolver.GetFormatterWithVerify<global::Intense.Master.ResultMaster>().Serialize(ref writer, (global::Intense.Master.ResultMaster)value, options);
                        break;
                    case 8:
                        options.Resolver.GetFormatterWithVerify<global::Intense.Master.SoundSheetNameMaster>().Serialize(ref writer, (global::Intense.Master.SoundSheetNameMaster)value, options);
                        break;
                    case 9:
                        options.Resolver.GetFormatterWithVerify<global::Intense.Master.TutorialStepMaster>().Serialize(ref writer, (global::Intense.Master.TutorialStepMaster)value, options);
                        break;
                    case 10:
                        options.Resolver.GetFormatterWithVerify<global::Intense.Master.TutorialMaster>().Serialize(ref writer, (global::Intense.Master.TutorialMaster)value, options);
                        break;
                    default:
                        break;
                }

                return;
            }

            writer.WriteNil();
        }

        public global::Intense.Master.BaseMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            if (reader.ReadArrayHeader() != 2)
            {
                throw new InvalidOperationException("Invalid Union data was detected. Type:global::Intense.Master.BaseMaster");
            }

            var key = reader.ReadInt32();

            if (!this.keyToJumpMap.TryGetValue(key, out key))
            {
                key = -1;
            }

            global::Intense.Master.BaseMaster result = null;
            switch (key)
            {
                case 0:
                    result = (global::Intense.Master.BaseMaster)options.Resolver.GetFormatterWithVerify<global::Intense.Master.VersionMaster>().Deserialize(ref reader, options);
                    break;
                case 1:
                    result = (global::Intense.Master.BaseMaster)options.Resolver.GetFormatterWithVerify<global::Intense.Master.TitleMaster>().Deserialize(ref reader, options);
                    break;
                case 2:
                    result = (global::Intense.Master.BaseMaster)options.Resolver.GetFormatterWithVerify<global::Intense.Master.SongSelectMaster>().Deserialize(ref reader, options);
                    break;
                case 3:
                    result = (global::Intense.Master.BaseMaster)options.Resolver.GetFormatterWithVerify<global::Intense.Master.SongMaster>().Deserialize(ref reader, options);
                    break;
                case 4:
                    result = (global::Intense.Master.BaseMaster)options.Resolver.GetFormatterWithVerify<global::Intense.Master.SongScoreRateMaster>().Deserialize(ref reader, options);
                    break;
                case 5:
                    result = (global::Intense.Master.BaseMaster)options.Resolver.GetFormatterWithVerify<global::Intense.Master.SongJudgeZoneMaster>().Deserialize(ref reader, options);
                    break;
                case 6:
                    result = (global::Intense.Master.BaseMaster)options.Resolver.GetFormatterWithVerify<global::Intense.Master.SongHpRateMaster>().Deserialize(ref reader, options);
                    break;
                case 7:
                    result = (global::Intense.Master.BaseMaster)options.Resolver.GetFormatterWithVerify<global::Intense.Master.ResultMaster>().Deserialize(ref reader, options);
                    break;
                case 8:
                    result = (global::Intense.Master.BaseMaster)options.Resolver.GetFormatterWithVerify<global::Intense.Master.SoundSheetNameMaster>().Deserialize(ref reader, options);
                    break;
                case 9:
                    result = (global::Intense.Master.BaseMaster)options.Resolver.GetFormatterWithVerify<global::Intense.Master.TutorialStepMaster>().Deserialize(ref reader, options);
                    break;
                case 10:
                    result = (global::Intense.Master.BaseMaster)options.Resolver.GetFormatterWithVerify<global::Intense.Master.TutorialMaster>().Deserialize(ref reader, options);
                    break;
                default:
                    reader.Skip();
                    break;
            }

            return result;
        }
    }


}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name


// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Intense.Master
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class VersionMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.VersionMaster>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public VersionMasterFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "Version", 0 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Version"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.VersionMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(1);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[0]));
            writer.Write(value.Version);
        }

        public global::Intense.Master.VersionMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __Version__ = default(int);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySequence<byte> stringKey = reader.ReadStringSequence().Value;
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __Version__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Intense.Master.VersionMaster();
            ____result.Version = __Version__;
            return ____result;
        }
    }

    public sealed class TitleMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.TitleMaster>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public TitleMasterFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "Tid", 0 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Tid"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.TitleMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(1);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[0]));
            writer.Write(value.Tid);
        }

        public global::Intense.Master.TitleMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __Tid__ = default(int);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySequence<byte> stringKey = reader.ReadStringSequence().Value;
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __Tid__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Intense.Master.TitleMaster();
            ____result.Tid = __Tid__;
            return ____result;
        }
    }

    public sealed class SongSelectMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.SongSelectMaster>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public SongSelectMasterFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "Group", 0 },
                { "StartSongTime", 1 },
                { "SongTime", 2 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Group"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("StartSongTime"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("SongTime"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.SongSelectMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(3);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[0]));
            writer.Write(value.Group);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[1]));
            writer.Write(value.StartSongTime);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[2]));
            writer.Write(value.SongTime);
        }

        public global::Intense.Master.SongSelectMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __Group__ = default(int);
            var __StartSongTime__ = default(int);
            var __SongTime__ = default(int);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySequence<byte> stringKey = reader.ReadStringSequence().Value;
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __Group__ = reader.ReadInt32();
                        break;
                    case 1:
                        __StartSongTime__ = reader.ReadInt32();
                        break;
                    case 2:
                        __SongTime__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Intense.Master.SongSelectMaster();
            ____result.Group = __Group__;
            ____result.StartSongTime = __StartSongTime__;
            ____result.SongTime = __SongTime__;
            return ____result;
        }
    }

    public sealed class SongMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.SongMaster>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public SongMasterFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "Sid", 0 },
                { "Group", 1 },
                { "Difficulty", 2 },
                { "Name", 3 },
                { "Composer", 4 },
                { "Start_offset", 5 },
                { "Bg", 6 },
                { "Score", 7 },
                { "Hp", 8 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Sid"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Group"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Difficulty"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Name"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Composer"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Start_offset"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Bg"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Score"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Hp"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.SongMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(9);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[0]));
            writer.Write(value.Sid);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[1]));
            writer.Write(value.Group);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[2]));
            writer.Write(value.Difficulty);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[3]));
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Name, options);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[4]));
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Composer, options);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[5]));
            writer.Write(value.Start_offset);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[6]));
            writer.Write(value.Bg);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[7]));
            writer.Write(value.Score);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[8]));
            writer.Write(value.Hp);
        }

        public global::Intense.Master.SongMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __Sid__ = default(int);
            var __Group__ = default(int);
            var __Difficulty__ = default(int);
            var __Name__ = default(string);
            var __Composer__ = default(string);
            var __Start_offset__ = default(float);
            var __Bg__ = default(int);
            var __Score__ = default(int);
            var __Hp__ = default(int);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySequence<byte> stringKey = reader.ReadStringSequence().Value;
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __Sid__ = reader.ReadInt32();
                        break;
                    case 1:
                        __Group__ = reader.ReadInt32();
                        break;
                    case 2:
                        __Difficulty__ = reader.ReadInt32();
                        break;
                    case 3:
                        __Name__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 4:
                        __Composer__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 5:
                        __Start_offset__ = reader.ReadSingle();
                        break;
                    case 6:
                        __Bg__ = reader.ReadInt32();
                        break;
                    case 7:
                        __Score__ = reader.ReadInt32();
                        break;
                    case 8:
                        __Hp__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Intense.Master.SongMaster();
            ____result.Sid = __Sid__;
            ____result.Group = __Group__;
            ____result.Difficulty = __Difficulty__;
            ____result.Name = __Name__;
            ____result.Composer = __Composer__;
            ____result.Start_offset = __Start_offset__;
            ____result.Bg = __Bg__;
            ____result.Score = __Score__;
            ____result.Hp = __Hp__;
            return ____result;
        }
    }

    public sealed class SongScoreRateMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.SongScoreRateMaster>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public SongScoreRateMasterFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "Type", 0 },
                { "Rate", 1 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Type"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Rate"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.SongScoreRateMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(2);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[0]));
            writer.Write(value.Type);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[1]));
            writer.Write(value.Rate);
        }

        public global::Intense.Master.SongScoreRateMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __Type__ = default(int);
            var __Rate__ = default(float);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySequence<byte> stringKey = reader.ReadStringSequence().Value;
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __Type__ = reader.ReadInt32();
                        break;
                    case 1:
                        __Rate__ = reader.ReadSingle();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Intense.Master.SongScoreRateMaster();
            ____result.Type = __Type__;
            ____result.Rate = __Rate__;
            return ____result;
        }
    }

    public sealed class SongJudgeZoneMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.SongJudgeZoneMaster>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public SongJudgeZoneMasterFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "Type", 0 },
                { "Zone", 1 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Type"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Zone"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.SongJudgeZoneMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(2);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[0]));
            writer.Write(value.Type);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[1]));
            writer.Write(value.Zone);
        }

        public global::Intense.Master.SongJudgeZoneMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __Type__ = default(int);
            var __Zone__ = default(float);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySequence<byte> stringKey = reader.ReadStringSequence().Value;
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __Type__ = reader.ReadInt32();
                        break;
                    case 1:
                        __Zone__ = reader.ReadSingle();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Intense.Master.SongJudgeZoneMaster();
            ____result.Type = __Type__;
            ____result.Zone = __Zone__;
            return ____result;
        }
    }

    public sealed class SongHpRateMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.SongHpRateMaster>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public SongHpRateMasterFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "Type", 0 },
                { "Rate", 1 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Type"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Rate"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.SongHpRateMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(2);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[0]));
            writer.Write(value.Type);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[1]));
            writer.Write(value.Rate);
        }

        public global::Intense.Master.SongHpRateMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __Type__ = default(int);
            var __Rate__ = default(int);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySequence<byte> stringKey = reader.ReadStringSequence().Value;
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __Type__ = reader.ReadInt32();
                        break;
                    case 1:
                        __Rate__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Intense.Master.SongHpRateMaster();
            ____result.Type = __Type__;
            ____result.Rate = __Rate__;
            return ____result;
        }
    }

    public sealed class ResultMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.ResultMaster>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public ResultMasterFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "Rid", 0 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Rid"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.ResultMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(1);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[0]));
            writer.Write(value.Rid);
        }

        public global::Intense.Master.ResultMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __Rid__ = default(int);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySequence<byte> stringKey = reader.ReadStringSequence().Value;
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __Rid__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Intense.Master.ResultMaster();
            ____result.Rid = __Rid__;
            return ____result;
        }
    }

    public sealed class SoundSheetNameMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.SoundSheetNameMaster>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public SoundSheetNameMasterFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "Category", 0 },
                { "Id", 1 },
                { "SheetName", 2 },
                { "CueName", 3 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Category"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Id"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("SheetName"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("CueName"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.SoundSheetNameMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(4);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[0]));
            writer.Write(value.Category);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[1]));
            writer.Write(value.Id);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[2]));
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.SheetName, options);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[3]));
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.CueName, options);
        }

        public global::Intense.Master.SoundSheetNameMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __Category__ = default(int);
            var __Id__ = default(int);
            var __SheetName__ = default(string);
            var __CueName__ = default(string);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySequence<byte> stringKey = reader.ReadStringSequence().Value;
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __Category__ = reader.ReadInt32();
                        break;
                    case 1:
                        __Id__ = reader.ReadInt32();
                        break;
                    case 2:
                        __SheetName__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __CueName__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Intense.Master.SoundSheetNameMaster();
            ____result.Category = __Category__;
            ____result.Id = __Id__;
            ____result.SheetName = __SheetName__;
            ____result.CueName = __CueName__;
            return ____result;
        }
    }

    public sealed class TutorialStepMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.TutorialStepMaster>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public TutorialStepMasterFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "Tid", 0 },
                { "StepOrder", 1 },
                { "Description", 2 },
                { "TriggerTime", 3 },
                { "HintPositionX", 4 },
                { "HintPositionY", 5 },
                { "IsSkippable", 6 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Tid"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("StepOrder"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Description"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("TriggerTime"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("HintPositionX"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("HintPositionY"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("IsSkippable"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.TutorialStepMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(7);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[0]));
            writer.Write(value.Tid);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[1]));
            writer.Write(value.StepOrder);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[2]));
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Description, options);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[3]));
            writer.Write(value.TriggerTime);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[4]));
            writer.Write(value.HintPositionX);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[5]));
            writer.Write(value.HintPositionY);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[6]));
            writer.Write(value.IsSkippable);
        }

        public global::Intense.Master.TutorialStepMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __Tid__ = default(int);
            var __StepOrder__ = default(int);
            var __Description__ = default(string);
            var __TriggerTime__ = default(float);
            var __HintPositionX__ = default(float);
            var __HintPositionY__ = default(float);
            var __IsSkippable__ = default(bool);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySequence<byte> stringKey = reader.ReadStringSequence().Value;
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __Tid__ = reader.ReadInt32();
                        break;
                    case 1:
                        __StepOrder__ = reader.ReadInt32();
                        break;
                    case 2:
                        __Description__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __TriggerTime__ = reader.ReadSingle();
                        break;
                    case 4:
                        __HintPositionX__ = reader.ReadSingle();
                        break;
                    case 5:
                        __HintPositionY__ = reader.ReadSingle();
                        break;
                    case 6:
                        __IsSkippable__ = reader.ReadBoolean();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Intense.Master.TutorialStepMaster();
            ____result.Tid = __Tid__;
            ____result.StepOrder = __StepOrder__;
            ____result.Description = __Description__;
            ____result.TriggerTime = __TriggerTime__;
            ____result.HintPositionX = __HintPositionX__;
            ____result.HintPositionY = __HintPositionY__;
            ____result.IsSkippable = __IsSkippable__;
            return ____result;
        }
    }

    public sealed class TutorialMasterFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Intense.Master.TutorialMaster>
    {


        private readonly global::MessagePack.Internal.AutomataDictionary ____keyMapping;
        private readonly byte[][] ____stringByteKeys;

        public TutorialMasterFormatter()
        {
            this.____keyMapping = new global::MessagePack.Internal.AutomataDictionary()
            {
                { "Tid", 0 },
                { "Title", 1 },
                { "Description", 2 },
                { "Sid", 3 },
                { "Order", 4 },
                { "IsRequired", 5 },
                { "VoiceCue", 6 },
                { "HintText", 7 },
                { "Type", 8 },
            };

            this.____stringByteKeys = new byte[][]
            {
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Tid"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Title"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Description"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Sid"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Order"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("IsRequired"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("VoiceCue"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("HintText"),
                global::MessagePack.Internal.CodeGenHelpers.GetEncodedStringBytes("Type"),
            };
        }

        public void Serialize(ref MessagePackWriter writer, global::Intense.Master.TutorialMaster value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteMapHeader(9);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[0]));
            writer.Write(value.Tid);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[1]));
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Title, options);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[2]));
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Description, options);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[3]));
            writer.Write(value.Sid);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[4]));
            writer.Write(value.Order);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[5]));
            writer.Write(value.IsRequired);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[6]));
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.VoiceCue, options);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[7]));
            formatterResolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.HintText, options);
            writer.WriteRaw(new ReadOnlySequence<byte>(this.____stringByteKeys[8]));
            writer.Write(value.Type);
        }

        public global::Intense.Master.TutorialMaster Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var __Tid__ = default(int);
            var __Title__ = default(string);
            var __Description__ = default(string);
            var __Sid__ = default(int);
            var __Order__ = default(int);
            var __IsRequired__ = default(bool);
            var __VoiceCue__ = default(string);
            var __HintText__ = default(string);
            var __Type__ = default(int);

            for (int i = 0; i < length; i++)
            {
                ReadOnlySequence<byte> stringKey = reader.ReadStringSequence().Value;
                int key;
                if (!this.____keyMapping.TryGetValue(stringKey, out key))
                {
                    reader.Skip();
                    continue;
                }

                switch (key)
                {
                    case 0:
                        __Tid__ = reader.ReadInt32();
                        break;
                    case 1:
                        __Title__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 2:
                        __Description__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 3:
                        __Sid__ = reader.ReadInt32();
                        break;
                    case 4:
                        __Order__ = reader.ReadInt32();
                        break;
                    case 5:
                        __IsRequired__ = reader.ReadBoolean();
                        break;
                    case 6:
                        __VoiceCue__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 7:
                        __HintText__ = formatterResolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
                        break;
                    case 8:
                        __Type__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Intense.Master.TutorialMaster();
            ____result.Tid = __Tid__;
            ____result.Title = __Title__;
            ____result.Description = __Description__;
            ____result.Sid = __Sid__;
            ____result.Order = __Order__;
            ____result.IsRequired = __IsRequired__;
            ____result.VoiceCue = __VoiceCue__;
            ____result.HintText = __HintText__;
            ____result.Type = __Type__;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

