// <auto-generated />
using Intense.Master;
using MasterMemory;
using MessagePack;
using System;
using System.Collections.Generic;
using Master.Tables;

namespace Master
{
   public sealed class MemoryDatabase : MemoryDatabaseBase
   {
        public VersionMasterTable VersionMasterTable { get; private set; }
        public TitleMasterTable TitleMasterTable { get; private set; }
        public SongSelectMasterTable SongSelectMasterTable { get; private set; }
        public SongMasterTable SongMasterTable { get; private set; }
        public SongScoreRateMasterTable SongScoreRateMasterTable { get; private set; }
        public SongJudgeZoneMasterTable SongJudgeZoneMasterTable { get; private set; }
        public SongHpRateMasterTable SongHpRateMasterTable { get; private set; }
        public ResultMasterTable ResultMasterTable { get; private set; }
        public SoundSheetNameMasterTable SoundSheetNameMasterTable { get; private set; }
        public TutorialStepMasterTable TutorialStepMasterTable { get; private set; }
        public TutorialMasterTable TutorialMasterTable { get; private set; }

        public MemoryDatabase(
            VersionMasterTable VersionMasterTable,
            TitleMasterTable TitleMasterTable,
            SongSelectMasterTable SongSelectMasterTable,
            SongMasterTable SongMasterTable,
            SongScoreRateMasterTable SongScoreRateMasterTable,
            SongJudgeZoneMasterTable SongJudgeZoneMasterTable,
            SongHpRateMasterTable SongHpRateMasterTable,
            ResultMasterTable ResultMasterTable,
            SoundSheetNameMasterTable SoundSheetNameMasterTable,
            TutorialStepMasterTable TutorialStepMasterTable,
            TutorialMasterTable TutorialMasterTable
        )
        {
            this.VersionMasterTable = VersionMasterTable;
            this.TitleMasterTable = TitleMasterTable;
            this.SongSelectMasterTable = SongSelectMasterTable;
            this.SongMasterTable = SongMasterTable;
            this.SongScoreRateMasterTable = SongScoreRateMasterTable;
            this.SongJudgeZoneMasterTable = SongJudgeZoneMasterTable;
            this.SongHpRateMasterTable = SongHpRateMasterTable;
            this.ResultMasterTable = ResultMasterTable;
            this.SoundSheetNameMasterTable = SoundSheetNameMasterTable;
            this.TutorialStepMasterTable = TutorialStepMasterTable;
            this.TutorialMasterTable = TutorialMasterTable;
        }

        public MemoryDatabase(byte[] databaseBinary, bool internString = true, MessagePack.IFormatterResolver formatterResolver = null)
            : base(databaseBinary, internString, formatterResolver)
        {
        }

        protected override void Init(Dictionary<string, (int offset, int count)> header, System.ReadOnlyMemory<byte> databaseBinary, MessagePack.MessagePackSerializerOptions options)
        {
            this.VersionMasterTable = ExtractTableData<VersionMaster, VersionMasterTable>(header, databaseBinary, options, xs => new VersionMasterTable(xs));
            this.TitleMasterTable = ExtractTableData<TitleMaster, TitleMasterTable>(header, databaseBinary, options, xs => new TitleMasterTable(xs));
            this.SongSelectMasterTable = ExtractTableData<SongSelectMaster, SongSelectMasterTable>(header, databaseBinary, options, xs => new SongSelectMasterTable(xs));
            this.SongMasterTable = ExtractTableData<SongMaster, SongMasterTable>(header, databaseBinary, options, xs => new SongMasterTable(xs));
            this.SongScoreRateMasterTable = ExtractTableData<SongScoreRateMaster, SongScoreRateMasterTable>(header, databaseBinary, options, xs => new SongScoreRateMasterTable(xs));
            this.SongJudgeZoneMasterTable = ExtractTableData<SongJudgeZoneMaster, SongJudgeZoneMasterTable>(header, databaseBinary, options, xs => new SongJudgeZoneMasterTable(xs));
            this.SongHpRateMasterTable = ExtractTableData<SongHpRateMaster, SongHpRateMasterTable>(header, databaseBinary, options, xs => new SongHpRateMasterTable(xs));
            this.ResultMasterTable = ExtractTableData<ResultMaster, ResultMasterTable>(header, databaseBinary, options, xs => new ResultMasterTable(xs));
            this.SoundSheetNameMasterTable = ExtractTableData<SoundSheetNameMaster, SoundSheetNameMasterTable>(header, databaseBinary, options, xs => new SoundSheetNameMasterTable(xs));
            this.TutorialStepMasterTable = ExtractTableData<TutorialStepMaster, TutorialStepMasterTable>(header, databaseBinary, options, xs => new TutorialStepMasterTable(xs));
            this.TutorialMasterTable = ExtractTableData<TutorialMaster, TutorialMasterTable>(header, databaseBinary, options, xs => new TutorialMasterTable(xs));
        }

        public ImmutableBuilder ToImmutableBuilder()
        {
            return new ImmutableBuilder(this);
        }

        public DatabaseBuilder ToDatabaseBuilder()
        {
            var builder = new DatabaseBuilder();
            builder.Append(this.VersionMasterTable.GetRawDataUnsafe());
            builder.Append(this.TitleMasterTable.GetRawDataUnsafe());
            builder.Append(this.SongSelectMasterTable.GetRawDataUnsafe());
            builder.Append(this.SongMasterTable.GetRawDataUnsafe());
            builder.Append(this.SongScoreRateMasterTable.GetRawDataUnsafe());
            builder.Append(this.SongJudgeZoneMasterTable.GetRawDataUnsafe());
            builder.Append(this.SongHpRateMasterTable.GetRawDataUnsafe());
            builder.Append(this.ResultMasterTable.GetRawDataUnsafe());
            builder.Append(this.SoundSheetNameMasterTable.GetRawDataUnsafe());
            builder.Append(this.TutorialStepMasterTable.GetRawDataUnsafe());
            builder.Append(this.TutorialMasterTable.GetRawDataUnsafe());
            return builder;
        }
    }
}